from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ChallengeAssets: 


	# Click Rule Assets
	# 主界面-左上角头像(进入个人信息) 
	C_AVATAR = RuleClick(roi_front=(22,12,32,42), roi_back=(22,12,32,42), name="avatar")
	# 角色面板-左侧挑战页签 
	C_CHALLENGE_TAB = RuleClick(roi_front=(78,478,62,38), roi_back=(78,478,62,38), name="challenge_tab")


	# Image Rule Assets
	# 角色面板-顶部页签栏 
	I_CHARACTER_PANEL = RuleImage(roi_front=(300,8,820,62), roi_back=(300,8,820,62), threshold=0.8, method="Template matching", file="./tasks/Challenge/res/res_character_panel.png")
	# 挑战页-顶部页签栏 
	I_CHALLENGE_PAGE = RuleImage(roi_front=(290,10,800,60), roi_back=(290,10,800,60), threshold=0.8, method="Template matching", file="./tasks/Challenge/res/res_challenge_page.png")


