from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class YuwaiMimangAssets: 


	# Click Rule Assets
	# NPC对话弹窗-「进入域外迷窟」选项行点击区域（277,318,1003,378） 
	C_NPC_DIALOG_ENTER = RuleClick(roi_front=(277,318,726,60), roi_back=(277,318,726,60), name="npc_dialog_enter")
	# 小地图-NPC列表点击区域（950,180,1120,600），OCR定位迷窟守卫后点这里不行，实际点OCR坐标 
	C_MINIMAP_NPC_LIST = RuleClick(roi_front=(950,180,170,420), roi_back=(950,180,170,420), name="minimap_npc_list")
	# NPC对话弹窗-绿色关闭按钮点击区域（与素材同区域） 
	C_DIALOG_CLOSE = RuleClick(roi_front=(985,68,75,70), roi_back=(985,68,75,70), name="dialog_close")


	# Image Rule Assets
	# 小地图弹窗-「世界地图」按钮（弹窗存在性特征） 
	I_MINIMAP_PANEL = RuleImage(roi_front=(953,108,168,60), roi_back=(900,80,300,180), threshold=0.8, method="Template matching", file="./tasks/YuwaiMimang/res/res_minimap_panel.png")
	# NPC对话弹窗-右上角绿色关闭按钮（弹窗存在性特征；位置随场景会偏，roiBack 放宽） 
	I_NPC_DIALOG_X = RuleImage(roi_front=(985,68,75,70), roi_back=(940,30,180,140), threshold=0.8, method="Template matching", file="./tasks/YuwaiMimang/res/res_npc_dialog_x.png")
	# NPC对话弹窗-标题区（确认是迷窟守卫而不是别的NPC；弹窗位置会随分辨率有几十像素抖动，roiBack 放宽） 
	I_NPC_DIALOG_TITLE = RuleImage(roi_front=(490,105,300,55), roi_back=(400,60,520,140), threshold=0.75, method="Template matching", file="./tasks/YuwaiMimang/res/res_npc_dialog_title.png")
	# NPC对话弹窗-「进入域外迷窟」选项文字（点之前用它确认该行存在） 
	I_NPC_DIALOG_ENTER_TEXT = RuleImage(roi_front=(548,328,185,50), roi_back=(277,280,726,130), threshold=0.75, method="Template matching", file="./tasks/YuwaiMimang/res/res_npc_dialog.png")
	# NPC对话弹窗-「确定」按钮 
	I_DIALOG_CONFIRM = RuleImage(roi_front=(806,542,190,62), roi_back=(760,520,260,100), threshold=0.8, method="Template matching", file="./tasks/YuwaiMimang/res/res_dialog_confirm.png")
	# 域外迷窟-剩余怪物数量条（确认已进入迷窟地图） 
	I_INSIDE_REMAINING = RuleImage(roi_front=(430,578,260,45), roi_back=(380,560,360,80), threshold=0.75, method="Template matching", file="./tasks/YuwaiMimang/res/res_inside_remaining.png")
	# 域外迷窟-击败守卫者任务进度条（备用确认特征） 
	I_INSIDE_TASK = RuleImage(roi_front=(55,128,300,55), roi_back=(20,110,400,90), threshold=0.75, method="Template matching", file="./tasks/YuwaiMimang/res/res_inside_task.png")


	# Ocr Rule Assets
	# 小地图-NPC列表文本区（OCR找迷窟守卫，950,180,1120,600） 
	O_MINIMAP_NPC_TEXT = RuleOcr(roi=(950,180,170,420), area=(950,180,170,420), mode="Full", method="Default", keyword="迷窟守卫", name="minimap_npc_text")
	# 主页面右上角地点文字（确认已进入域外迷窟） 
	O_INSIDE_LOCATION = RuleOcr(roi=(1080,80,200,45), area=(1080,80,200,45), mode="Full", method="Default", keyword="域外迷窟", name="inside_location")
	# 域外迷窟-剩余怪物数量文字（读剩余怪物数用） 
	O_INSIDE_REMAINING_TEXT = RuleOcr(roi=(430,578,260,45), area=(430,578,260,45), mode="Full", method="Default", keyword="剩余怪物数量", name="inside_remaining_text")


