from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GameUiAssets: 


	# Click Rule Assets
	# 主页面点击头像进入角色面板 
	C_PAGE_MAIN_GOTO_PLAYER = RuleClick(roi_front=(22,20,49,50), roi_back=(22,20,49,50), name="page_main_goto_player")
	# 角色面板点击返回主页面 
	C_PAGE_PLAYER_BACK = RuleClick(roi_front=(1190,6,87,53), roi_back=(1190,6,87,53), name="page_player_back")


	# Image Rule Assets
	# 主页面特征（左下角图标） 
	I_PAGE_MAIN = RuleImage(roi_front=(21,676,24,17), roi_back=(13,658,49,44), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_main.png")
	# 角色-详情页特征（培养按钮） 
	I_PAGE_ROLE_DETAIL = RuleImage(roi_front=(632,365,97,44), roi_back=(597,352,171,74), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_role_detail.png")
	# 物品-背包页特征（整理背包按钮） 
	I_PAGE_ITEM_BAG = RuleImage(roi_front=(560,580,154,68), roi_back=(550,570,174,88), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_item_bag.png")
	# 挑战-战场页特征（你的战斗力文字） 
	I_PAGE_CHALLENGE = RuleImage(roi_front=(557,123,128,40), roi_back=(536,113,274,65), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_challenge.png")


	# Ocr Rule Assets
	# 角色面板左侧模块栏（OCR 识别区） 
	O_PANEL_SIDEBAR = RuleOcr(roi=(0,110,245,610), area=(0,110,245,610), mode="Full", method="Default", keyword="", name="panel_sidebar")
	# 角色面板顶部 tab 栏（OCR 识别区） 
	O_PANEL_TABS = RuleOcr(roi=(280,8,765,85), area=(280,8,765,85), mode="Full", method="Default", keyword="", name="panel_tabs")


