from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GameUiAssets: 


	# Click Rule Assets
	# 主页面点击头像进入角色面板 
	C_PAGE_MAIN_GOTO_PLAYER = RuleClick(roi_front=(22,20,49,50), roi_back=(22,20,49,50), name="page_main_goto_player")
	# 角色面板点击返回主页面 
	C_PAGE_PLAYER_BACK = RuleClick(roi_front=(1190,6,87,53), roi_back=(1190,6,87,53), name="page_player_back")
	# 活动弹窗右上角关闭按钮 
	C_ACTIVITY_CLOSE = RuleClick(roi_front=(1191,49,48,45), roi_back=(1191,49,48,45), name="activity_close")
	# 游戏通用弹窗-确定按钮（报名/参战） 
	C_DIALOG_CONFIRM = RuleClick(roi_front=(742,363,173,40), roi_back=(742,363,173,40), name="dialog_confirm")
	# 游戏通用弹窗-取消按钮（备用） 
	C_DIALOG_CANCEL = RuleClick(roi_front=(364,363,173,40), roi_back=(364,363,173,40), name="dialog_cancel")
	# 背包-整理背包按钮 
	C_BAG_SORT = RuleClick(roi_front=(573,591,137,48), roi_back=(573,591,137,48), name="bag_sort")
	# 主页面-点击右上角小地图打开小地图弹窗 
	C_MAP_MINIMAP_ENTRY = RuleClick(roi_front=(1208,18,62,54), roi_back=(1208,18,62,54), name="map_minimap_entry")
	# 世界地图-右上角关闭按钮（固定位置，关闭后回主页面） 
	C_MAP_WORLD_MAP_CLOSE = RuleClick(roi_front=(968,40,43,62), roi_back=(968,40,43,62), name="map_world_map_close")
	# 世界地图列表-右上角关闭按钮（关闭后回世界地图） 
	C_MAP_WORLD_MAP_LIST_CLOSE = RuleClick(roi_front=(983,45,46,53), roi_back=(983,45,46,53), name="map_world_map_list_close")
	# 传送确认弹窗-确定按钮（两种弹窗确认位置有偏差，这里取公共区域） 
	C_MAP_TELEPORT_CONFIRM = RuleClick(roi_front=(790,380,72,36), roi_back=(790,380,72,36), name="map_teleport_confirm")


	# Image Rule Assets
	# 主页面特征（右下角图标） 
	I_PAGE_MAIN = RuleImage(roi_front=(1229,676,24,17), roi_back=(1219,662,49,44), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_main.png")
	# 角色-详情页特征（培养按钮） 
	I_PAGE_ROLE_DETAIL = RuleImage(roi_front=(632,365,97,44), roi_back=(597,352,171,74), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_role_detail.png")
	# 物品-背包页特征（整理背包按钮） 
	I_PAGE_ITEM_BAG = RuleImage(roi_front=(560,580,154,68), roi_back=(550,570,174,88), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_item_bag.png")
	# 挑战-战场页特征（你的战斗力文字） 
	I_PAGE_CHALLENGE = RuleImage(roi_front=(557,123,128,40), roi_back=(536,113,274,65), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_challenge.png")
	# 右上角菜单收起状态（左箭头） 
	I_MENU_COLLAPSED = RuleImage(roi_front=(1148,31,18,26), roi_back=(1136,18,50,54), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_menu_collapsed.png")
	# 右上角菜单展开状态（右箭头） 
	I_MENU_EXPANDED = RuleImage(roi_front=(1153,28,15,32), roi_back=(1136,18,50,54), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_menu_expanded.png")
	# 右上角菜单内的活动图标 
	I_ACTIVITY_ICON = RuleImage(roi_front=(1087,36,31,32), roi_back=(448,12,685,71), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_activity_icon.png")
	# 活动-公告页特征（右侧内容面板顶边） 
	I_PAGE_ACTIVITY_NOTICE = RuleImage(roi_front=(531,183,655,23), roi_back=(528,169,672,80), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_activity_notice.png")
	# 活动-推荐页特征（活动奖励图标） 
	I_PAGE_ACTIVITY_LIST = RuleImage(roi_front=(1059,207,67,40), roi_back=(1045,197,92,59), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_activity_list.png")
	# 活动-世界首领页特征（奖按钮） 
	I_PAGE_ACTIVITY_WORLD_BOSS = RuleImage(roi_front=(158,554,45,41), roi_back=(135,541,90,65), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_activity_world_boss.png")
	# 活动弹窗容器特征（右上角绿X） 
	I_PAGE_ACTIVITY = RuleImage(roi_front=(1180,28,65,52), roi_back=(1150,10,130,90), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_activity.png")
	# 活动-活跃页特征（活跃值标题） 
	I_PAGE_ACTIVITY_ACTIVE = RuleImage(roi_front=(872,180,88,36), roi_back=(850,160,150,80), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_page_activity_active.png")
	# 小地图页-世界地图按钮（小地图页特征，也是进入世界地图的入口，位置随地图大小变化） 
	I_MAP_MINIMAP_WORLD_MAP = RuleImage(roi_front=(971,118,126,42), roi_back=(794,9,1210,314), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_map_minimap_world_map.png")
	# 世界地图页-列表按钮（世界地图页特征，点击进入世界地图列表） 
	I_MAP_WORLD_MAP_LIST_BUTTON = RuleImage(roi_front=(1008,587,73,45), roi_back=(988,570,114,84), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_map_world_map_list_button.png")
	# 世界地图列表页-「请选择」标题（列表页特征） 
	I_MAP_WORLD_MAP_LIST_PAGE = RuleImage(roi_front=(591,92,95,37), roi_back=(559,73,159,79), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_map_world_map_list_page.png")
	# 小地图-右上角关闭按钮（通用绿X，位置随弹窗大小变化） 
	I_MAP_POPUP_CLOSE = RuleImage(roi_front=(1131,44,41,51), roi_back=(1007,0,245,223), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_map_popup_close.png")
	# 传送确认弹窗-确定按钮（两种弹窗通用，按钮位置偏 19px） 
	I_MAP_DIALOG_CONFIRM_BUTTON = RuleImage(roi_front=(768,358,117,61), roi_back=(760,350,140,100), threshold=0.8, method="Template matching", file="./tasks/GameUi/res/res_map_dialog_confirm_button.png")


	# Ocr Rule Assets
	# 角色面板左侧模块栏（OCR 识别区） 
	O_PANEL_SIDEBAR = RuleOcr(roi=(0,110,245,610), area=(0,110,245,610), mode="Full", method="Default", keyword="", name="panel_sidebar")
	# 角色面板顶部 tab 栏（OCR 识别区） 
	O_PANEL_TABS = RuleOcr(roi=(280,8,765,85), area=(280,8,765,85), mode="Full", method="Default", keyword="", name="panel_tabs")
	# 活动弹窗顶部 tab 栏（OCR 识别区） 
	O_ACTIVITY_TABS = RuleOcr(roi=(140,80,950,65), area=(140,80,950,65), mode="Full", method="Default", keyword="", name="activity_tabs")
	# 活动弹窗右侧子 tab 栏（可上下滚动） 
	O_ACTIVITY_SUBTABS = RuleOcr(roi=(1045,150,175,480), area=(1045,150,175,480), mode="Full", method="Default", keyword="", name="activity_subtabs")
	# 游戏通用弹窗文案识别区域（报名/匹配/提示弹窗） 
	O_DIALOG_TEXT = RuleOcr(roi=(314,235,649,249), area=(331,234,622,259), mode="Full", method="Default", keyword="", name="dialog_text")
	# 活动-活跃页的任务列表 
	O_ACTIVITY_TASK_LIST = RuleOcr(roi=(105,225,550,370), area=(105,225,550,370), mode="Full", method="Default", keyword="", name="activity_task_list")
	# 物品-背包物品格（4 列）识别区 
	O_BAG_GRID = RuleOcr(roi=(255,105,925,450), area=(255,105,925,450), mode="Full", method="Default", keyword="", name="bag_grid")
	# 主页面右上角-当前地点与坐标（如 沼泽427,59） 
	O_MAP_LOCATION = RuleOcr(roi=(1072,84,208,35), area=(1072,84,208,35), mode="Full", method="Default", keyword="", name="map_location")
	# 世界地图列表-地点条目识别区（供按名称点击传送使用） 
	O_MAP_WORLD_MAP_LIST = RuleOcr(roi=(280,140,720,475), area=(280,140,720,475), mode="Full", method="Default", keyword="", name="map_world_map_list")
	# 传送确认弹窗-文案区（免费传送与花费铜贝两种弹窗都含「传送」） 
	O_MAP_TELEPORT_DIALOG = RuleOcr(roi=(300,240,680,140), area=(300,240,680,140), mode="Full", method="Default", keyword="传送", name="map_teleport_dialog")
	# 传送确认弹窗-确定按钮（OCR 定位后点击，兼容两种弹窗） 
	O_MAP_DIALOG_CONFIRM = RuleOcr(roi=(700,340,300,120), area=(700,340,300,120), mode="Full", method="Default", keyword="确定", name="map_dialog_confirm")


