from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DouXianGeAssets: 


	# Click Rule Assets
	# 斗仙阁-第一个挑战按钮(默认位置) 
	C_CHALLENGE_BUTTON = RuleClick(roi_front=(1151,342,85,42), roi_back=(1151,342,85,42), name="challenge_button")


	# Image Rule Assets
	# 斗仙阁-页面特征(商店/军阶/战绩/排行榜按钮) 
	I_DOUXIAN_PAGE = RuleImage(roi_front=(1019,126,228,126), roi_back=(1019,126,228,126), threshold=0.8, method="Template matching", file="./tasks/DouXianGe/res/res_douxian_page.png")
	# 斗仙阁-挑战按钮(列表内多处,roiBack为按钮列搜索区) 
	I_CHALLENGE_BUTTON = RuleImage(roi_front=(1151,342,85,42), roi_back=(1140,330,140,380), threshold=0.8, method="Template matching", file="./tasks/DouXianGe/res/res_challenge_button.png")


	# Ocr Rule Assets
	# 斗仙阁-今日剩余挑战次数 
	O_DOUXIAN_COUNT = RuleOcr(roi=(280,125,290,42), area=(280,125,290,42), mode="Full", method="Default", keyword="", name="douxian_count")
	# 斗仙阁-特权额外挑战次数 
	O_DOUXIAN_BONUS = RuleOcr(roi=(780,125,100,45), area=(780,125,100,45), mode="Full", method="Default", keyword="", name="douxian_bonus")


