from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ArenaAssets: 


	# Click Rule Assets
	# 战场-同服竞技按钮 
	C_ARENA_SAME_SERVER = RuleClick(roi_front=(1122,274,123,48), roi_back=(1122,274,123,48), name="arena_same_server")
	# 2人角斗按钮区域（双击报名用） 
	C_ARENA_BUTTON_CLICK = RuleClick(roi_front=(285,190,130,58), roi_back=(285,190,130,58), name="arena_button_click")


	# Image Rule Assets
	# 2人角斗按钮（同服竞技已选中） 
	I_ARENA_BUTTON_2P = RuleImage(roi_front=(293,198,102,38), roi_back=(277,177,142,81), threshold=0.8, method="Template matching", file="./tasks/Arena/res/res_arena_button_2p.png")


