from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class GlobalGameAssets: 


	# Click Rule Assets
	# 死亡弹窗-返回村子 
	C_DEATH_RETURN = RuleClick(roi_front=(486,264,310,58), roi_back=(486,264,310,58), name="death_return")


	# Image Rule Assets
	# 死亡弹窗-三个按钮区块 
	I_DEATH_DIALOG = RuleImage(roi_front=(486,255,310,260), roi_back=(486,255,310,260), threshold=0.8, method="Template matching", file="./tasks/GlobalGame/res/res_death_dialog.png")


