from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class WarChariotAssets: 


	# Click Rule Assets
	# 仙盟战车-参与点击区域（757,368,905,412） 
	C_CHARIOT_JOIN = RuleClick(roi_front=(757,368,148,44), roi_back=(757,368,148,44), name="chariot_join")


	# Ocr Rule Assets
	# 主页面-仙盟战车文字检测区域（343,274,941,346） 
	O_CHARIOT_TEXT = RuleOcr(roi=(343,274,598,72), area=(343,274,598,72), mode="Full", method="Default", keyword="仙盟战车", name="chariot_text")


