from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class QuizAssets: 


	# Click Rule Assets
	# 选项A点击区域 
	C_OPTION_A = RuleClick(roi_front=(159,285,439,50), roi_back=(583,156,100,100), name="option_a")
	# 选项B点击区域 
	C_OPTION_B = RuleClick(roi_front=(149,360,373,49), roi_back=(583,156,100,100), name="option_b")
	# 选项C点击区域 
	C_OPTION_C = RuleClick(roi_front=(151,439,385,45), roi_back=(583,156,100,100), name="option_c")


	# Image Rule Assets
	# 答题榜标题(判断是否在答题界面) 
	I_QUIZ_DIALOG = RuleImage(roi_front=(930,140,170,44), roi_back=(900,120,240,90), threshold=0.8, method="Template matching", file="./tasks/Quiz/res/res_quiz_dialog.png")
	# 回答正确提示 
	I_FEEDBACK_CORRECT = RuleImage(roi_front=(371,529,185,54), roi_back=(300,120,500,500), threshold=0.8, method="Template matching", file="./tasks/Quiz/res/res_feedback_correct.png")
	# 回答错误提示 
	I_FEEDBACK_WRONG = RuleImage(roi_front=(371,529,185,54), roi_back=(300,120,500,500), threshold=0.8, method="Template matching", file="./tasks/Quiz/res/res_feedback_wrong.png")
	# 答题结束图片 
	I_QUIZ_FINISH = RuleImage(roi_front=(425,155,81,87), roi_back=(300,120,500,500), threshold=0.8, method="Template matching", file="./tasks/Quiz/res/res_quiz_finish.png")
	# 关闭答题界面按钮 
	I_CLOSE = RuleImage(roi_front=(1140,76,50,52), roi_back=(1100,50,140,110), threshold=0.8, method="Template matching", file="./tasks/Quiz/res/res_close.png")


	# Ocr Rule Assets
	# 第X/20题 
	O_PROGRESS = RuleOcr(roi=(108,138,173,42), area=(108,138,173,42), mode="Full", method="Default", keyword="", name="progress")
	# 题干文字 
	O_QUESTION = RuleOcr(roi=(105,178,705,88), area=(105,178,705,88), mode="Full", method="Default", keyword="", name="question")
	# A选项文字(不含前缀) 
	O_OPTION_A = RuleOcr(roi=(190,277,609,63), area=(190,277,609,63), mode="Full", method="Default", keyword="", name="option_a")
	# B选项文字(不含前缀) 
	O_OPTION_B = RuleOcr(roi=(190,353,609,62), area=(190,353,609,62), mode="Full", method="Default", keyword="", name="option_b")
	# C选项文字(不含前缀) 
	O_OPTION_C = RuleOcr(roi=(190,427,609,62), area=(190,427,609,62), mode="Full", method="Default", keyword="", name="option_c")


