from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class XianfuJiuchongtianAssets: 


	# Click Rule Assets
	# 仙府九重天-弹窗关闭(绿X, x,y,w,h) 
	C_POPUP_CLOSE = RuleClick(roi_front=(1174,133,45,52), roi_back=(1174,133,45,52), name="popup_close")
	# 过关奖励-翻牌(第5张) 
	C_REWARD_CARD = RuleClick(roi_front=(840,300,80,170), roi_back=(840,300,80,170), name="reward_card")
	# 大关按钮-增长天 
	C_DAGUAN_TAB_1 = RuleClick(roi_front=(325,172,120,54), roi_back=(325,172,120,54), name="daguan_tab_1")
	# 大关按钮-多闻天 
	C_DAGUAN_TAB_2 = RuleClick(roi_front=(325,252,120,54), roi_back=(325,252,120,54), name="daguan_tab_2")
	# 大关按钮-持国天 
	C_DAGUAN_TAB_3 = RuleClick(roi_front=(325,332,120,54), roi_back=(325,332,120,54), name="daguan_tab_3")
	# 大关按钮-广目天 
	C_DAGUAN_TAB_4 = RuleClick(roi_front=(325,412,120,54), roi_back=(325,412,120,54), name="daguan_tab_4")
	# 增长天-第1小关 
	C_S1_1 = RuleClick(roi_front=(572,463,65,62), roi_back=(572,463,65,62), name="s1_1")
	# 增长天-第2小关 
	C_S1_2 = RuleClick(roi_front=(819,458,68,66), roi_back=(819,458,68,66), name="s1_2")
	# 增长天-第3小关 
	C_S1_3 = RuleClick(roi_front=(741,258,73,67), roi_back=(741,258,73,67), name="s1_3")
	# 增长天-第4小关 
	C_S1_4 = RuleClick(roi_front=(970,222,90,66), roi_back=(970,222,90,66), name="s1_4")
	# 多闻天-第1小关 
	C_S2_1 = RuleClick(roi_front=(595,357,86,61), roi_back=(595,357,86,61), name="s2_1")
	# 多闻天-第2小关 
	C_S2_2 = RuleClick(roi_front=(782,466,80,53), roi_back=(782,466,80,53), name="s2_2")
	# 多闻天-第3小关 
	C_S2_3 = RuleClick(roi_front=(828,237,82,64), roi_back=(828,237,82,64), name="s2_3")
	# 多闻天-第4小关 
	C_S2_4 = RuleClick(roi_front=(1010,310,83,64), roi_back=(1010,310,83,64), name="s2_4")
	# 持国天-第1小关 
	C_S3_1 = RuleClick(roi_front=(586,229,80,55), roi_back=(586,229,80,55), name="s3_1")
	# 持国天-第2小关 
	C_S3_2 = RuleClick(roi_front=(691,444,85,56), roi_back=(691,444,85,56), name="s3_2")
	# 持国天-第3小关 
	C_S3_3 = RuleClick(roi_front=(853,250,70,63), roi_back=(853,250,70,63), name="s3_3")
	# 持国天-第4小关 
	C_S3_4 = RuleClick(roi_front=(1027,426,71,54), roi_back=(1027,426,71,54), name="s3_4")
	# 广目天-第1小关 
	C_S4_1 = RuleClick(roi_front=(588,425,84,57), roi_back=(588,425,84,57), name="s4_1")
	# 广目天-第2小关 
	C_S4_2 = RuleClick(roi_front=(710,242,90,59), roi_back=(710,242,90,59), name="s4_2")
	# 广目天-第3小关 
	C_S4_3 = RuleClick(roi_front=(851,435,101,61), roi_back=(851,435,101,61), name="s4_3")
	# 广目天-第4小关 
	C_S4_4 = RuleClick(roi_front=(1006,255,101,55), roi_back=(1006,255,101,55), name="s4_4")


	# Image Rule Assets
	# 仙府九重天-页面特征(仙府说明按钮) 
	I_XIANFU_PAGE = RuleImage(roi_front=(1100,638,146,46), roi_back=(1100,638,146,46), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_xianfu_page.png")
	# 仙府九重天-增长天按钮 
	I_ZENGZHANG = RuleImage(roi_front=(325,172,120,54), roi_back=(325,172,120,54), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_zengzhang.png")
	# 仙府九重天-增长天第一关岛屿 
	I_STAGE_1 = RuleImage(roi_front=(555,455,95,90), roi_back=(555,455,95,90), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_stage_1.png")
	# 关卡详情-开始挑战按钮 
	I_START_CHALLENGE = RuleImage(roi_front=(845,585,130,55), roi_back=(845,585,130,55), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_start_challenge.png")
	# 过关奖励面板标题 
	I_REWARD_PANEL = RuleImage(roi_front=(640,185,180,45), roi_back=(640,185,180,45), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_reward_panel.png")
	# 大关1-增长天特征(回纹) 
	I_DAGUAN_1 = RuleImage(roi_front=(549,444,109,84), roi_back=(549,444,109,84), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_daguan_1.png")
	# 大关2-多闻天特征(云纹) 
	I_DAGUAN_2 = RuleImage(roi_front=(563,321,152,132), roi_back=(563,321,152,132), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_daguan_2.png")
	# 大关3-持国天特征(太极棕) 
	I_DAGUAN_3 = RuleImage(roi_front=(548,206,143,129), roi_back=(548,206,143,129), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_daguan_3.png")
	# 大关4-广目天特征(太极黑白) 
	I_DAGUAN_4 = RuleImage(roi_front=(554,402,157,121), roi_back=(554,402,157,121), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_daguan_4.png")
	# 背包-空物品格特征（整页出现说明下面没物品了） 
	I_BAG_EMPTY = RuleImage(roi_front=(266,115,76,81), roi_back=(255,105,925,450), threshold=0.8, method="Template matching", file="./tasks/XianfuJiuchongtian/res/res_bag_empty.png")


	# Ocr Rule Assets
	# 仙府九重天-剩余仙石(X/40) 
	O_XIANFU_STONE = RuleOcr(roi=(755,620,270,60), area=(755,620,270,60), mode="Full", method="Default", keyword="", name="xianfu_stone")
	# 过关奖励-恭喜您获得 XXX（翻牌结果） 
	O_XIANFU_REWARD = RuleOcr(roi=(560,528,420,42), area=(560,528,420,42), mode="Full", method="Default", keyword="", name="xianfu_reward")


