from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AncientHuntAssets: 


	# Click Rule Assets
	# 主界面-目标锁定按钮(点文字中心,避开左侧按钮) 
	C_TARGET_BUTTON_CLICK = RuleClick(roi_front=(1226,270,28,18), roi_back=(1226,270,28,18), name="target_button_click")
	# 主界面-攻击/交互按钮（锁定目标后点它弹出交互框） 
	C_ATTACK = RuleClick(roi_front=(1146,597,82,60), roi_back=(1146,597,82,60), name="attack")


	# Image Rule Assets
	# 上古狩猎-交互框「进入上古狩猎场」按钮 
	I_ENTER_HUNT = RuleImage(roi_front=(527,323,218,53), roi_back=(505,305,262,89), threshold=0.8, method="Template matching", file="./tasks/AncientHunt/res/res_enter_hunt.png")
	# 主界面-目标锁定按钮（与世界首领同一个按钮） 
	I_TARGET_BUTTON = RuleImage(roi_front=(1217,235,33,43), roi_back=(1199,223,71,69), threshold=0.8, method="Template matching", file="./tasks/AncientHunt/res/res_target_button.png")


	# Ocr Rule Assets
	# 主界面-当前锁定目标名称（彩色描边字，用灰度放大整行识别） 
	O_TARGET_NAME = RuleOcr(roi=(426,5,240,36), area=(426,5,240,36), mode="Full", method="Default", keyword="", name="target_name")


