from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class AncientHuntAssets: 


	# Image Rule Assets
	# 上古狩猎-交互框「进入上古狩猎场」按钮 
	I_ENTER_HUNT = RuleImage(roi_front=(527,323,218,53), roi_back=(505,305,262,89), threshold=0.8, method="Template matching", file="./tasks/AncientHunt/res/res_enter_hunt.png")


